version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: amina
      POSTGRES_PASSWORD: 1919
    ports:
      - "5433:5432"  # Переадресуем на свободный порт, чтобы избежать конфликта
    volumes:
      - db_value:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U amina -d foodgram"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static_value:/app/static
      - media_value:/app/media
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    image: andyplo/foodgram_frontend:v.21.12.22
    platform: linux/amd64  # Добавлено для поддержки ARM (Mac M1/M2)
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
    restart: always

volumes:
  db_value:
  static_value:
  media_value:
